import { defaultStyling } from "@/modules/general/libs/defaults";

const BlogDisclaimer = () => {
  return (
    <div className={defaultStyling.blog.disclaimer}>
      All articles and images are generated by AI (Gemini 3)
    </div>
  );
};

export default BlogDisclaimer;
