const directories = [
  "https://websitelaunches.com/",
  "https://peerpush.net/",
  "https://www.hot100.ai/",
  "https://launched.lovable.app/",
  "https://indiehackers.com/",
  "https://dang.ai/",
  "https://salespopups.com/",
  "https://www.saashub.com/",
  "https://betalist.com/",
  "https://alternative.me/",
  "https://www.futuretools.io/",
  "https://devhunt.org/",
  "https://toolsfine.com/",
  "https://open-launch.com/",
  "https://ideakiln.com/",
  "https://acidtools.com/",
  "https://microlaunch.net/",
  "https://tinystartups.com/",
  "https://openalternative.co/",
  "https://www.launchingnext.com/",
  "https://trustmrr.com/",
  "https://rankyourai.com/",
  "https://toolfio.com/",
  "https://productburst.com/",
  "https://www.bestofweb.site/",
  "https://dirstarter.com/",
  "https://euroalternative.co/",
  "https://resource.fyi/",
  "https://www.saaspa.ge/",
  "https://esidehustles.com/",
  "https://madewithlovable.com/",
  "https://producthunt.com",
  "https://foundrlist.com"
]

export default directories;